services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: dumblydorr
      POSTGRES_USER: dumblydorr
      POSTGRES_PASSWORD: localpassword # This will only be used for local testing and not production users or passwords
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
